# Generated by Django 4.2.9 on 2024-02-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('short_name', models.CharField(max_length=10)),
                ('img', models.CharField(max_length=400)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
