# Generated by Django 4.2.9 on 2024-02-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='short_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
